version: '3.8'

services:
  app:
    image: luobaigu/arc_workpiece_measurement_system:1.0
    # build:
    #   context: ..
    #   dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/ArcWorkpiece-Measurement-System:cached
    command: sleep infinity
    networks:
      - arcworkpiece-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: arcworkpiece
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - arcworkpiece-network

networks:
  arcworkpiece-network:
    driver: bridge

volumes:
  mysql-data:
